language: python

sudo: false

cache:
  pip: true
  directories:
    - $HOME/pypy

matrix:
  include:
    # remove "-dev" once 3.7 proper exists on travis-ci
    - name: "3.7: test, doc, coverage"
      python: 3.7-dev
      install:
        pip install --upgrade cython numpy pytest matplotlib scipy ipython sphinx sphinx_rtd_theme jupyter pytest-cov codecov
      script:
        COVERAGE=1 make cov &&
        make test-notebooks &&
        make doc &&
        codecov

    - name: "osx: test"
      os: osx
      language: sh
      install:
        pip install --user --upgrade cython numpy pytest matplotlib scipy
      script:
        make test

    - name: "pypy3.5: test"
      language: sh
      install:
        source ci-scripts/install_pypy.sh
      script:
        make test

    - name: "2.7: sdist"
      python: 2.7
      install:
        pip install --upgrade cython numpy
      script:
        source ci-scripts/travis_sdist_test.sh

    - name: "3.7: sdist"
      python: 3.7-dev
      install:
        pip install --upgrade cython numpy
      script:
        source ci-scripts/travis_sdist_test.sh

  allow_failures:
    - name: "pypy3.5: test"
